#!/usr/bin/env python3

import numpy as np
from PIL import Image

import argparse
import pathlib

desc_string = 'Script to convert image file to an numpy binary file'

parser = argparse.ArgumentParser(description=desc_string)

parser.add_argument('image_file', type=pathlib.Path, nargs='?',
                    help='Image file path')
parser.add_argument('-o', '--out', dest='destanation_file',
                    type=pathlib.Path, required=False, nargs='?',
                    help='Output npy file destanation')

args = parser.parse_args()

if args.destanation_file is None:
    args.destanation_file = pathlib.Path('./output.npy')


if not args.image_file.exists():
    print('Error: input file does not exists')
    exit()

image = Image.open(args.image_file.absolute())
np.save(args.destanation_file, image)
